# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Audio', max_length=50)),
                ('audio', models.FileField(upload_to='media/')),
                ('upload_dt', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
