# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='name',
        ),
    ]
