# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_remove_music_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='name',
            field=models.CharField(default='Audio', max_length=50),
        ),
    ]
